### PR TITLE
feat: all EE 2024 VAA features

### LINKED ISSUE #21: As a Voter, I want to see matching scores for Parties as well.

### LINKED ISSUE #35: Store settings values in backend

### LINKED ISSUE #46: Add Strapi token to the frontend dynamically
If needed, update the documentation. The `/documentation/docker-setup-guide.md` file has some references to this topic.

### LINKED ISSUE #57: Create an EntityList component to be used throughout the application
The Candidate List component is a component that can be reused throughout the application.

image

See [Figma Designs](https://www.figma.com/file/uY9RTeNGmkSXjBYEWMmgGn/Election-Compass?node-id=297%3A5805&t=ZM8SK3lSAyXPV506-0)

### LINKED ISSUE #107: As an Application Admin, I want to be able to modify the look and feel of the application without coding.
To start off, we'll utilize the `tailwind.config.cjs` file to establish universal styles and provide the app with a cohesive appearance. However, those rules should be changed depending on some Strapi values. If it is not possible to change the values of the `tailwind.config.cjs` file. We may need to think on how to allow the application manager to change the look and feel of the app.

### LINKED ISSUE #110: Load candidate Image from Strapi

### LINKED ISSUE #142: Refactor: More logical file structure for the matching algorithm
Make the file structure of the matching algorithm more logical, make some small adjustments and write a better README.

### 1. File structure

Split most of the multi-type files into separate ones and maybe organise them into folders like this (while providing exports at /index.ts):

- algorithms (just the main matching algo)
- answer
- distance
- match (the match objects)
- question
- space
- _test
- _examples

### 2. Other adjustments

- Change `MISSING_VALUE` to `null | undefined` so that it doesn't necessarily need to be imported by consumers of the module.
- Get rid lof`getMatchableAnswerValue`, `MatchableValue` etc. and only expect `MatchableQuestion` to provide `normalizeValue(value: unknown): MatchingSpaceCoordinate | MatchingSpaceCoordinate[]`.

### LINKED ISSUE #170: Figure out a way to reset localStorage when necessary
The stored voter answers are reset with `resetLocalStorage`when clicking on the link to `/intro`.

We're using localStorage, so they [never expire automatically.](https://developer.mozilla.org/en-US/docs/Web/API/Web_Storage_API)

For a future proof version, we should probably store smth like the application version and/or electionId as well and clear the storage if these have changed. For mock data generation, it could also update some random property, we could additionally check against.

We should probably also expire them after a certain time.

### LINKED ISSUE #173: Fix question ordering
Fetcth types, then categories ordered by order with questions populated. Or the other way round.

At the same time, also separate the info questions into groups in `<CandidateBasicInfo>`.

### LINKED ISSUE #175: Create a loading spinner component and use it whenever waiting for page data to load
When created, also use in `frontend/src/lib/components/authentication/RequireLogin.svelte`

### LINKED ISSUE #213: As a Voter, I want to see all the candidates answers and opinions on a single page
The voters should be able to see the answers and opinions the candidates give.

image

https://www.figma.com/file/3LDNZWOxuhhVaVPAOApfOK/Voting-Advice-Application?type=design&node-id=0-1&mode=design&t=jJu4jZLFbpmqT1bn-0

### LINKED ISSUE #217: Fix radial ScoreGauge
- Add the background color for the unfilled area
- Decrease the size or make it adjustable

### LINKED ISSUE #256: Update DaisyUI to version 4
There's a cpla [breaking changes](https://github.com/saadeghi/daisyui/blob/master/CHANGELOG.md#changelog) that need to fixed at the same time.

1. Change all direct CSS vars to use `oklch(var(--p))` instead of `hsl()`
2. `--btn-text-case` CSS var is no longer used and can be removed from `tailwind.config.cjs`

At the same time, also check that `modal` works properly. See [discussion](https://github.com/OpenVAA/voting-advice-application/pull/316#discussion_r1443812843).

### LINKED ISSUE #272: Mock data generation should not generate a default candidate user when running in production/public internet
Current mock data generation creates a candidate user with default password and username while it's run. This is fine for local development, but while pushing the app to the public internet this should be disabled as otherwise anyone can log in as an user and edit data from there as the credentials are found in the source code, and removing the user or changing the password can be easily overlooked.

### LINKED ISSUE #276: Add description about the project to README.md
- Add some information about OpenVAA project, it's intended uses etc
- Add info about pulling Docker images & installing those on a server for deployment

### LINKED ISSUE #360: build: create public endpoints for data in Strapi to get rid of API token
Currently a read-only API token needs to be generated in Strapi for the Voter App to work (see docs). This is clunky and makes setup needlessly complicated.

It also prevents client-side fetching of data unless data routes are added to Sveltekit.

Furthermore, it prevents the inclusion of end-to-end tests in the CI/CD Github actions because they would need access to the API token. 

To fix these issues, publicly available API endpoints should be created in Strapi for all of the data needed by the Voter App. At the same time, the data returned could be cleaned up a bit (see `/lib/api/getData` for how it needs to be parsed now).

### Update

Optionally, we could just give the same read privileges to unauthenticated users as are now granted with the API key. This would be very easy to accomplish.

### Check whether Drafts can be read if API token is used

### LINKED ISSUE #368: feat: create info and help pages
Create pages for basic information content.

### LINKED ISSUE #371: feat: Alert component for displaying notifications
This will be needed, for example, for the saved data prompt: #370

### LINKED ISSUE #373: feat: enable question category selection
Enable selection of questions to answer by selecting categories.

At the same time, the frontend data model may need to be changed so that questions are contained in categories and not vice versa.

This was implemented in an old draft: #141

### LINKED ISSUE #374: feat: enable colours for Parties
Categories need to have a theme colour,  this can be added as a `color` property of the `Question Category` objects. `Parties` already have this, but it has no effect in the frontend.

The color should be applied to the category term when shown next to the questions and possibly in category headings (in the Candidate App). This implies changes to the frontend data types, such that the `category` of a `QuestionProp` is an object instead of just a string containing the name.

For parties, the colour should be applied to the party flag icon. This, in turn, would possibly imply changes to the `Icon` component to allow for a custom color in addition to the named ones. This would differ from the so that the it would:
- either automatically create a different version for use in dark mode
- accept to colors, `customColorLight` and `customColorDark` for use in light and dark modes

Finally, before using any of the colors in the frontend, the colour should be automatically modified to have sufficient contrast on `base-1/300`. Possibly:
- use the formula for contrast calculation in this [discussion](https://stackoverflow.com/questions/65304462/is-it-possible-to-make-a-javascript-program-that-changes-the-color-of-the-text-t)
- either lighten or darken by mixing with black or white and either solve for correct color analytically or iteratively ([example here](https://medium.com/confrere/automatically-creating-an-accessible-color-palette-from-any-color-sure-e735c3f2f45e), although it uses a dep)

### LINKED ISSUE #377: feat: update the Results page to match designs
The Results page currently does not follow the designs. It should also allow switching between candidate and party results.
- Implementing the filters is a separate issue: #378
- The Election selector may be implemented later.

image

### LINKED ISSUE #378: feat: basic result filters and sorting
It should be possible to filter and sort the results based on criteria defined in the basic info. Ultimately, we would want to support filtering by any field, but a subset is enough for the time being.

The basic filters include:
- Party
- Gender
- Age (if supplied)
- Name or free text
- Match score (only for sorting)

More advanced filters for future consideration include:
- Agreement on a specific question

The filters will need both a store-based functional implementation as well as UI components. They could be optionally included in the Candidate list component #57

### LINKED ISSUE #379: refactor: update EntityCard to support variable formats
For the YouthVAA/Allianssi VAA, we need a more flexible `EntityCard` component. It should support the views below:

For Candidates:
image

For Parties:
image
- This also necessitates an additional field for `Parties` that contains the EU-level party they belong to ("Sosialistien ja demokraattien ryhmä"). This might be treated as an `Electoral Alliance` in this case, although normally we would display the other parties belonging to that if that were the case…

And optionally:

image

image

### LINKED ISSUE #380: refactor: match Candidate page styling to design
Update to match the design:

image

### LINKED ISSUE #381: feat: Party page
Make a similar page for `Parties` that now exists for `Candidates`.

### LINKED ISSUE #382: refactor: make sure tabbed navigation is possible
Currently `(Entity)Card`s use an `on:click` handler for opening them, which prevents opening them in new tabs. In addition, we have to listen to keyboard events to make opening them accessible.

It would be better if these could be wrapped in an `<a>` tag.

### LINKED ISSUE #383: feat: enable analytics for research and prompt user for permission
Make sure we can collect anonymized usage data in a flexible manner.

At first, this can be implemented using GA, such that all loggable actions call a common analytics function, which then uses GA or some other analytics tool defined in the settings.

On the frontend pages or in the components when the user performs some action, e.g. answer a question, we would call a common function like `logEvent('answer', {questionId, answerValue})`. The function would check from the app `settings` whether this event type is to be logged and with which details (e.g. do we save the answer value), and then either immediately or periodically save the event in a way that maintains the user session id and event number or reliable timestamp.

Note that the user may have the app open in multiple tabs.

It would be nice to show an opt in/out checkbox at the start of the app as well, although this might have to be some kind of notification bc the user might arrive directly on a subpage.

### LINKED ISSUE #384: feat: user survey prompt
Enable showing a prompt to complete a user survey when certain criteria are met (time elapsed, questions answered, X candidates viewed etc.).

### LINKED ISSUE #385: feat: pipeline for importing data into Strapi
Create a pipeline that can be used to periodically import data from external sources into Strapi so that ids are maintained.

The data is foremost:
- Candidate info
- Candidate Answers
- Question texts
- Parties (likely done only initially)

### LINKED ISSUE #386: feat: Party matching
Enable calculating an average match for `Parties` in the matching algorithm.

### LINKED ISSUE #387: feat: optional video content
Enable showing of video content on pages. This is needed for the YouthVAA/Allianssi VAA.

Pages initially affected:
- introduction
- results
- question pages

Settings:
- Whether video content is enabled can initially be a static setting, but it could be a (custom) property that can be set in Strapi.

Features:
- Switching between video and text in the UI
- A persistent user preference for showing text instead of video
- Video controls: mute, pause, back/fwd between checkpoints in the video
- Tap controls: back/fwd between checkpoints in the video in the same way as in IG stories

See:
- https://svelte.dev/examples/media-elements
- For CORS issues: https://kit.svelte.dev/docs/configuration
- https://developer.mozilla.org/en-US/docs/Web/HTML/Element/video#attributes
- https://developer.mozilla.org/en-US/docs/Web/Media/Audio_and_video_delivery/Adding_captions_and_subtitles_to_HTML5_video
- https://developer.mozilla.org/en-US/docs/Web/Media/Autoplay_guide

### LINKED ISSUE #389: Small updates to Strapi content model
1. Make QuestionCategory.type required. This is needed for opinion and info questions to be found at all. (EDIT: This is not possible bc it's a relation.)
2. Remove Candidate Attributes and any references to it (postponed)
3. Add color and colorDark properties to Party and QuestionCategory
4. Add an App Settings content type which includes:
    - Publisher name
    - App/Publisher logo (light and dark)
5. Possibly edit unathenticated user privileges at the same time, see #360
6. Add filterable to Question.
7. Fix issues in #417 
8. Fix appLabel mock data generation issue after Strapi update

### LINKED ISSUE #396: feat: colors for Question Categories
See #374

Implement at the same time as the required content model changes: #389

At the same time, update the `SubMatches` component as well.

### LINKED ISSUE #417: fix: acl policies for some Voter App routes
With the new access control policies, some `getData` calls no longer work, such as:
- fetching a single nominated candidate
- fetching parties

The applicable filters and populate options need to be whitelisted.

### LINKED ISSUE #492: i18n: clean up translations and translate to Finnish

### LINKED ISSUE #516: Enable starting from any question

### LINKED ISSUE #519: Convert Questions to promises

### LINKED ISSUE #520: Quick 1–5 survey on results page

### LINKED ISSUE #521: Swedish translations

### LINKED ISSUE #522: Enable easy text search for parties

### LINKED ISSUE #523: Merge candidates and parties routes with results, also make filters work with both rankings and candidates

### LINKED ISSUE #524: Update matching algorithm so that entity and possibly question types are maintained in returns

### LINKED ISSUE #525: Link question type

### LINKED ISSUE #526: When loading Voter Answers disregard those that do not match any available questions

### LINKED ISSUE #527: Chain video so that muting status is maintained

### LINKED ISSUE #528: feat: create setting for hiding question category text
Sometimes question category names are informative only and should not be shown together with question texts.

One way would be to make this a property of the question categories themselves, but it's maybe easier to just make it a global setting.

### LINKED ISSUE #538: chore: merge EE 2024 branches to main

### LINKED ISSUE #542: feat: allow optional skipping of a question category
In the YouthVAA app, we want to allow skipping of "Values" questions when the user has finished the other opinion questions.

### PR DESCRIPTION
**Pull request by kaljarv**
## WHY:

This massive PR combines all the features added for the EU Elections 2024 VAAs, including the video-enabled VAA and the more traditional one with more advanced handling of question categories. This PR contains all the content from the following earlier PRs:

- #543
- #498
- #494
- #493
- #460
- #443
- #425
- #395

Fixes:

- Fixes #21
- Fixes #35
- Fixes #46
- Fixes #57
- Fixes #107
- Fixes #110
- Fixes #142
- Fixes #170
- Fixes #173
- Fixes #175
- Fixes #213
- Fixes #217
- Fixes #256
- Fixes #272
- Fixes #276
- Fixes #360
- Fixes #367
- Fixes #368
- Fixes #371
- Fixes #373
- Fixes #374
- Fixes #377
- Fixes #378
- Fixes #379
- Fixes #380
- Fixes #381
- Fixes #382
- Fixes #383
- Fixes #384
- Fixes #385
- Fixes #386
- Fixes #387
- Fixes #389
- Fixes #396
- Fixes #417
- Fixes #492
- Fixes #516
- Fixes #519
- Fixes #520
- Fixes #521
- Fixes #522
- Fixes #523
- Fixes #524
- Fixes #525
- Fixes #526
- Fixes #527
- Fixes #528
- Fixes #538
- Fixes #542

### What has been changed (if possible, add screenshots, gifs, etc. )

A lot.

## Check off each of the following tasks as they are completed

- [x] I have reviewed the changes myself in this PR. Please check the [self-review document](https://github.com/OpenVAA/voting-advice-application/blob/main/docs/contributing/self-review.md)
- [x] I have added or edited unit tests.
- [x] I have run the unit tests successfully.
- [x] I have run the e2e tests successfully.
- [x] I have tested this change on my own device.
- [x] I have tested this change on other devices (Using Browserstack is recommended).
- [x] I have tested my changes using the [WAVE extension](https://wave.webaim.org/extension/)
- [x] I have added documentation where necessary.
- [x] Is there an existing issue linked to this PR?

**Clean up your git commit history before submitting the pull request!**

### CODE REVIEW

**Review by norppaa — APPROVED** [review]
Start page has 3 i18n texts that do not work (one button and two in the footer). Otherwise it looks like it is working as intended.

**Comment by kaljarv** [comment]
> Start page has 3 i18n texts that do not work (one button and two in the footer). Otherwise it looks like it is working as intended.

Oh, I think this is because of the remote `App Labels` not having all the keys. I'll disable mock data generation for those, so that we rely on the local translations only until we can automate defining the `App Labels` content type so that it's always up-to-date with the local translations. See #507

**Review by anolpe — APPROVED** [review]
Didn't find anything that wasn't working :+1:

**Comment by kaljarv** [comment]
For some reason `maildev` is unhealthy now, but I'm merging this and adding a new issue about that, because the e2e test pass locally.

**Pull request merged**
